#!/usr/bin/env bash
# Install the load balancer

# Update package repositories
sudo apt-get update

# Upgrade installed packages
sudo apt-get -y upgrade

# Install HAProxy
sudo apt-get -y install haproxy

# Enable HAProxy by setting ENABLED=1
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Backup the original HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

# Add server configurations to the HAProxy configuration file
if grep -q "6058-lb-01" /etc/haproxy/haproxy.cfg; then
    echo "Server configurations already exist in HAProxy configuration file."
else
    sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF
listen 6058-lb-01
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 6058-web-01 3.92.139.185:80 check
    server 6058-web-02 54.173.48.37:80 check
EOF
fi

# Restart HAProxy service to apply changes
sudo service haproxy restart
