#!/usr/bin/env bash
# Commands to install Nginx on Web-Sever-01

# Updating Packages before making Installations
sudo apt-get update
sudo apt-get -y install nginx

# Configuring the Uncomplicated Firewall (UFW) to allow incoming traffic for the Nginx HTTP service
sudo ufw allow 'Nginx HTTP'

# Creating an index.html page
echo "Holberton School" | sudo tee /var/www/html/index.html > /dev/null

# Testing Nginx configurations for Syntax errors
sudo nginx -t

# Restarting Nginx
sudo service nginx restart

# Querying Nginx with curl and checking for "Holberton School" string in the response
if curl -s http://localhost | grep -q "Holberton School"; then
    echo "Nginx is serving the page with 'Holberton School'."
else
    echo "Nginx is not serving the page with 'Holberton School'."
fi

